# These are supported funding model platforms

# GitHub Sponsors
github: [Samarth208P]

# Buy Me a Coffee - One-time donations and memberships
buy_me_a_coffee: samarth208p

# Custom sponsorship URLs - Direct crypto payment options
custom: ['ethereum:0xEe4055Dd5E4896aC50f308eE7846037490482F1f', 'https://etherscan.io/address/0xEe4055Dd5E4896aC50f308eE7846037490482F1f']
